# users
ERROR_CREATE_POST = 100
ERROR_DUPULICATE_POST = 110

# other
NETWORK_ERROR = 999

ERROR_MESSAGES = {}
ERROR_MESSAGES[ERROR_CREATE_POST] = "記事作成時にエラーが起こりました。"
ERROR_MESSAGES[ERROR_DUPULICATE_POST] = "その記事は登録されています。"
ERROR_MESSAGES[NETWORK_ERROR] = "ネットワークエラーが起こりました。"
